## this is now stored in git so don't put passwords here!!

defaults: &defaults
  host: localhost
  port: 6379
  db: 0
  cache_db: 2

development:
  <<: *defaults

test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
